Controllers/AppointmentsController.cs
using Doctor_Appointment.Data;
using Doctor_Appointment.Models;
using Doctor_Appointment.Repo;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Doctor_Appointment.Controllers
{
    [Authorize(Roles = "Patient")]
    public class AppointmentsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _user;

        public IAppointmentRepo Repo { get; }

        public AppointmentsController(ApplicationDbContext context, IAppointmentRepo repo, SignInManager<IdentityUser> manager, UserManager<IdentityUser> user)
        {
            _context = context;
            Repo = repo;
            _signInManager = manager;
            _user = user;
        }

        // GET: Appointments

        [Authorize]
        public IActionResult Index()
        {
            var patId = _context.Patients.First(p => p.IdentityId == User.Claims.First().Value).PatientID;

            ViewBag.date = _context.Appointments.Select(a => a.dailyAvailbility.Dayid);

            return View(Repo.GetAll(patId));

        }

        // GET: Appointments/Details/5
        public IActionResult Details(int id)
        {
            if (_context.Appointments == null)
            {
                return NotFound();
            }

            var appointment = _context.Appointments
                .Include(a => a.doctor)
                .Include(a => a.patient)
                .Where(m => m.appointmentID == id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(Repo.GetById(id));
        }

        // GET: Appointments/Create
        public IActionResult Create(int Docid)
        {
            //ViewData["DoctorID"] = new SelectList(_context.Doctors.Include(d=>d.availableDays), "DoctorID", "FullName");
            //ViewData["PatientID"] = new SelectList(_context.Patients, "PatientID", "FullName");

            //var DoctorDates = _context.Doctors.Include(d => d.availableDays)
            //    .Select(d=> new {docId=d.DoctorID ,DocName=d.FullName , dates=d.availableDays
            //    .Select(a=>a.date).Distinct()}).ToList();

            ViewBag.DoctorDates = _context.Doctors.Include(d => d.availableDays)
            .FirstOrDefault(d => d.DoctorID == Docid);

            ViewData["DoctorID"] = new SelectList(_context.Doctors, "DoctorID", "FullName");
            var patient = _context.Patients.First(p => p.IdentityId == User.Claims.First().Value);
            ViewData["PatientID"] = patient.PatientID;

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Appointment appointment)
        {
            if (ModelState.IsValid)
            {

                try
                {
                    Repo.Insert(appointment);

                    return RedirectToAction("Index", "PayPal");

                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                }
            }
            else
                return NotFound();
        }

        // GET: Appointments/Edit/5
        public IActionResult Edit(int id)
        {
            ViewBag.date = _context.Appointments.Select(a => a.dailyAvailbility.Dayid);

            if (_context.Appointments == null)
            {
                return NotFound();
            }

            var appointment = _context.Appointments.FirstOrDefault(a => a.appointmentID == id);
            if (appointment == null)
            {
                return NotFound();
            }
            return View();
        }

        // POST: Appointments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("DoctorID,PatientID,AppointmentDay,AppointmentTime,AppointmentType,MedicalHistory")] Appointment appointment)
        {


            if (ModelState.IsValid)
            {
                try
                {
                    Repo.Update(appointment.DoctorID, appointment.PatientID, appointment);
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                }
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        // GET: Appointments/Delete/5
        public async Task<IActionResult> Delete(int Docid, int Patid)
        {
            ViewBag.date = _context.Appointments.Select(a => a.dailyAvailbility.Dayid);

            var appointment = await _context.Appointments
                .Include(a => a.doctor)
                .Include(a => a.patient)
                .FirstOrDefaultAsync(m => m.DoctorID == Docid && m.PatientID == Patid);

            if (appointment != null)
            {
                Repo.Delete(appointment.DoctorID, appointment.PatientID);
            }

            return View();
        }

        // POST: Appointments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int DocId, int PatId)
        {
            //if (_context.Appointments == null)
            //{
            //    return Problem("Entity set 'MedcareDbContext.Appointments'  is null.");
            //}
            var appointment = _context.Appointments.FirstOrDefault(m => m.DoctorID == DocId && m.PatientID == PatId);
            if (appointment != null)
            {
                Repo.Delete(DocId, PatId);

            }
            return RedirectToAction(nameof(Index));
        }

        private bool AppointmentExists(int id)
        {
            return (_context.Appointments?.Any(e => e.DoctorID == id)).GetValueOrDefault();
        }
    }
}

Controllers/DoctorsController.cs
using Doctor_Appointment.Data;
using Doctor_Appointment.Models;
using Doctor_Appointment.Repo;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace Doctor_Appointment.Controllers
{
    [Authorize(Roles = "Doctor")]
    public class DoctorsController : Controller
    {
        public ApplicationDbContext Context { get; }
        public IDoctorRepo doctor { get; }
        public IDailyAvailbilityRepo AvailbilityRepo { get; }

        public DoctorsController(ApplicationDbContext context , IDoctorRepo _doctor)
        {
            Context = context;
            doctor = _doctor;
        }

        [AllowAnonymous]
        // GET: DoctorsController
        public ActionResult Index()
        {
            return View(doctor.GetAll());
        }

        // GET: DoctorsController/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            var check = Context.Doctors.FirstOrDefault(c=>c.DoctorID==id);
           
            if(check!=null)
            {
                try
                {

                    return View(doctor.GetById(id));
                }
                catch(Exception ex)
                {
                    throw new Exception(ex.Message);
                }

            }
              return NotFound();
        }

       
        // GET: DoctorsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DoctorsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Doctor doc )
        {
            try
            {
                doctor.Insert(doc);

                return RedirectToAction("Create", "DailyAvailbilities");
            }
            catch
            {
                return View();
            }
        }

        // GET: DoctorsController/Edit/5
        public ActionResult Edit(int id)
        {
            var doc=Context.Doctors.FirstOrDefault(d=>d.DoctorID==id);
            if(doc!=null) 
            {
            return View(doc);
            }
            return View();

        }

        // POST: DoctorsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Doctor doc , DailyAvailbility dail)
        {
            try
            {
                doctor.Update(id,doc, dail);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        //GET: DoctorsController/Delete/5
        public IActionResult Delete(int id)
        {
            doctor.Delete(id);
            return RedirectToAction(nameof(Create));
        }

        //// POST: DoctorsController/Delete/5
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        doctor.Delete(id);
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

Controllers/HomeController.cs
using Doctor_Appointment.Data;
using Doctor_Appointment.Models;
using Doctor_Appointment.Repo;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;
using System.Numerics;

namespace Doctor_Appointment.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public ApplicationDbContext Context { get; }
        public IDoctorRepo DoctorRepo { get; }


        public HomeController(ILogger<HomeController> logger , ApplicationDbContext context, IDoctorRepo doctorRepo)
        {
            _logger = logger;
            Context = context;
            DoctorRepo = doctorRepo;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


        [HttpGet]
        public ActionResult SpecialistFilter()
        {
            ViewBag.Spectialist = Context.Doctors.ToList();

            return View(DoctorRepo.GetAll());
        }

        [HttpPost]
        public ActionResult SpecialistFilter(Spectialist spl)
        {
            ViewBag.Spectialist = Context.Doctors.ToList();

            if ((Context.Doctors.Any(s => s.specialist == spl)))
            {
                List<Doctor> spldoc = DoctorRepo.GetBySpecialist(spl);
                
                return View(spldoc);

            }
            return View();

        }


    }
}

Views/Home/AllDoc.cshtml
@model IEnumerable<Doctor_Appointment.Models.Doctor>

@{
    ViewData["Title"] = "AllDoc";
}

<h1>AllDoc</h1>


<form method="post" asp-controller="Doctors" action="SpecialistFilter">
 <select name="filterDoc">
    @foreach(var spl in Model)
    {
            <option value="@spl.specialist">@spl.ToString()</option>
    }
    </select>
    <input type="submit" value="Search"/>
</form>



<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.specialist)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Degree)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Clinic_Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Clinic_PhonNum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HomeExamination)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WatingTime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) 
{
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.specialist)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Degree)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Clinic_Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Clinic_PhonNum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HomeExamination)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WatingTime)
            </td>
            <td>
                <a asp-action="Create" asp-controller="Appointments" asp-route-id="@item.DoctorID">Book</a> |
                <a asp-action="Details" asp-controller="Doctors" asp-route-id="@item.DoctorID">Details</a> |
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/SpecialistFilter.cshtml
@model IEnumerable<Doctor_Appointment.Models.Doctor>

@{
    ViewData["Title"] = "SpecialistFilter";
}

<h1>AllDoc</h1>


<form method="post" action="/Home/SpecialistFilter">
   
    <select name="filterDoc">
        @foreach (var spl in ViewBag.Spectialist)
        {
            <option value="@spl.specialist">@spl.ToString()</option>
        }
    </select>
    
    <input type="submit" value="Search" />
</form>



<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.specialist)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Degree)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Clinic_Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Clinic_PhonNum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HomeExamination)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WatingTime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FullName)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.specialist)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Degree)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Clinic_Location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Clinic_PhonNum)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HomeExamination)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WatingTime)
                </td>
                <td>
                    <a asp-action="Details" asp-controller="Doctors" asp-route-id="@item.DoctorID">Details</a> 
                </td>
            </tr>
        }
    </tbody> 
</table>